name: floraad # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A Source Code Manager | A git alternative # 79 char long summary
description: |
  It comes with the following features

  *  GUI by default. This provides more comfort.
  *  Ability to fix commits messages.
  *  Deletion of old commits
  *  Saves data to Google Cloud Storage, thereby have low costs footprints.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64


parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    build-packages:
      - libwebkit2gtk-4.0-dev


apps:
  floraad:
    command: bin/floraad
    extensions: [gnome-3-34]
    plugs:
      - network-bind
      - network
